# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml
stages:
  - build_service
  - containerize
  - release_tagging

build-service:
  image: gitlab/gitlab-runner:alpine
  stage: build_service
  script:
    - ./build.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never
  artifacts:
    paths:
      - resources/golang-for-developers.md
    expire_in: 1 week

docker-build:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never
  variables:
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_MEMORY_REQUEST: 2048Mi
    KUBERNETES_MEMORY_LIMIT: 2048Mi
  needs: ["build-service"]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID

release_job:
  stage: release_tagging
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: docker-build
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never
  script:
    - echo "running release_job for $CI_PIPELINE_IID"
  release:
    name: 'Release $CI_PIPELINE_IID'
    description: 'Created using the release-cli'
    tag_name: '$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'