// Code generated by go-swagger; DO NOT EDIT.

package fridge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"codecentric.de/beer-fridge-go-swagger/models"
)

// GetTemperatureOKCode is the HTTP code returned for type GetTemperatureOK
const GetTemperatureOKCode int = 200

/*GetTemperatureOK return the current fridge temperature

swagger:response getTemperatureOK
*/
type GetTemperatureOK struct {

	/*
	  In: Body
	*/
	Payload models.Temperature `json:"body,omitempty"`
}

// NewGetTemperatureOK creates GetTemperatureOK with default headers values
func NewGetTemperatureOK() *GetTemperatureOK {

	return &GetTemperatureOK{}
}

// WithPayload adds the payload to the get temperature o k response
func (o *GetTemperatureOK) WithPayload(payload models.Temperature) *GetTemperatureOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get temperature o k response
func (o *GetTemperatureOK) SetPayload(payload models.Temperature) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTemperatureOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
