// Code generated by go-swagger; DO NOT EDIT.

// Package restapi A beer fridge service
//
//  Beer fridge service build with go-swagger
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/de.codecentric.go-workshop.beer-fridge.v1+json
//
//  Produces:
//    - application/de.codecentric.go-workshop.beer-fridge.v1+json
//
// swagger:meta
package restapi
