// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Beer defines key criteria of a beer
type Beer struct {
	ID           string `json:"id"`
	Manufacturer string `json:"manufacturer"`
	Name         string `json:"name"`
	// Origin of the beer as ISO country code
	Origin     string  `json:"origin"`
	Type       string  `json:"type"`
	Percentage float64 `json:"percentage"`
	Ibu        *int    `json:"ibu"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
