consumes:
- application/de.codecentric.go-workshop.beer-fridge.v1+json
info:
  description: Beer fridge service build with go-swagger
  title: A beer fridge service
  version: 1.0.0
produces:
- application/de.codecentric.go-workshop.beer-fridge.v1+json
schemes:
- http
swagger: "2.0"
definitions:
  beer:
    type: object
    required:
      - title
      - origin
      - volume-percentage
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      title:
        type: string
        minLength: 1
      origin:
        type: string
        minLength: 1
      volume-percentage:
        type: number
        format: float
        minLength: 1
  temperature:
    type: integer
    format: int64
    readOnly: true
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /beers:
    get:
      operationId: getAllBeers
      tags:
        - beers
      parameters:
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the beer operations
          schema:
            type: array
            items:
              $ref: "#/definitions/beer"
    post:
      tags:
        - beers
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/beer"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/beer"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /beers/{id}:
    delete:
      tags:
        - beers
      operationId: destroyOne
      parameters:
        - type: integer
          format: int64
          name: id
          in: path
          required: true
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /temperature:
    get:
      operationId: getTemperature
      tags:
        - fridge
      responses:
        200:
          description: return the current fridge temperature
          schema:
            $ref: "#/definitions/temperature"
