// Code generated by go-swagger; DO NOT EDIT.

package fridge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetTemperatureParams creates a new GetTemperatureParams object
//
// There are no default values defined in the spec.
func NewGetTemperatureParams() GetTemperatureParams {

	return GetTemperatureParams{}
}

// GetTemperatureParams contains all the bound params for the get temperature operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTemperature
type GetTemperatureParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTemperatureParams() beforehand.
func (o *GetTemperatureParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
