// Code generated by go-swagger; DO NOT EDIT.

package beers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"codecentric.de/beer-fridge-go-swagger/models"
)

// GetAllBeersOKCode is the HTTP code returned for type GetAllBeersOK
const GetAllBeersOKCode int = 200

/*GetAllBeersOK list the beer operations

swagger:response getAllBeersOK
*/
type GetAllBeersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Beer `json:"body,omitempty"`
}

// NewGetAllBeersOK creates GetAllBeersOK with default headers values
func NewGetAllBeersOK() *GetAllBeersOK {

	return &GetAllBeersOK{}
}

// WithPayload adds the payload to the get all beers o k response
func (o *GetAllBeersOK) WithPayload(payload []*models.Beer) *GetAllBeersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all beers o k response
func (o *GetAllBeersOK) SetPayload(payload []*models.Beer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllBeersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Beer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
