
on:
  push:
    branches:
      - 'main'

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./build.sh
#  docker:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          tags: user/app:latest
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: docker/metadata-action@v3
#        id: metadata
#        with:
#          images: ghcr.io/${{ github.repository }}
#      - uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - uses: int128/kaniko-action@v1
#        with:
#          push: true
#          labels: ${{ steps.metadata.outputs.labels }}
#          cache: true
#          cache-repository: ghcr.io/${{ github.repository }}/cache
#          tags: ${{github.run_number}}
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./build.sh
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: go-tour
          tag: ${{github.run_number}}
          cache: true
          cache_registry: cache